Django 101/feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView
app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('post/', AddPostView.as_view(), name='post')
]

Django 101/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace = 'feed')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django 101/feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text

Django 101/feed/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.FileField()  
    text = forms.CharField(label="Description")
    

Django 101/feed/views.py
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm
from .models import Post
from django.contrib import messages

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class = PostForm
    success_url = "/" 

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, "Your post was successful!")
        return super().form_valid(form)

Django 101/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    {% include "includes/navbar.html" %}

    {% if messages %}
        {% for message in messages %}
        <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %} 
            bg-gradient text-center text-white py-4">  
                {{ message }}
        </div>     
        {% endfor %}
    {% endif %}    
    
      <div class="container">
        {% block body %}{% endblock %}
      </div>
</body>
</html>

Django 101/templates/detail.html
{% extends 'base.html' %}

{% block title %}Detail view {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-10 offset-sm-1 py-5 text-center">
           <p> {{ object.text }} </p>
            <img src ="{{ object.image.url }}" class="img-fluid rounded">
        </div>
    </div>
{% endblock %}

Django 101/templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}My super awesome homepage{% endblock %}

{% block body %}
    <div class="row">
        {% for post in posts %}
            <div class="col-sm-6 col-md-3">
                <div class="card my-4">
                    {% thumbnail post.image "200x200" crop="center" as im %}
                        <img src="{{ im.url }}" class="card-img-top" alt="...">
                    {% endthumbnail %} 
                    <div class="card-body">
                        <p class="card-text">{{ post.text }}</p>
                        <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Full Image</a>
                    </div>
                </div>
            </div>
        
        {% empty %}
            <div class="col-sm-6 offset-3 text-center py-5 my-5">
                <h3>Welcome!</h3>
                <p>Upload your first image?</p>
                <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload Image</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Django 101/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Image Sharer</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Add New Image</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

Django 101/templates/new_post.html
{% extends 'base.html' %}

{% block title %}Upload a new image{% endblock %}

{% block body %}
    <form method="POST" action="" enctype ="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
    <h2>Upload an image!</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button type="submit" class="btn btn-success">Submit form</button>
    </div>
    </form>
{% endblock %}